import './globals.css'
import { Inter } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Navbar from './components/navbar';
import { cookies } from 'next/headers'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const cookieStore = cookies()
  const cook = cookieStore.get('appSession');
  return (
    <html lang="en">
      <UserProvider>
      <body className={inter.className}>
      <div style={{position:"fixed",zIndex:1,width:"100%"}}>
        <Navbar cook={cook}/>

      </div>

     {children}
       
        </body>
      </UserProvider>
    </html>
  )
}
